# escape = `
ARG WINDOWS_RELEASE=1809

FROM golang:1.25.0-nanoserver AS base
WORKDIR \Source
COPY go.mod go.sum \Source\
RUN go mod download
COPY . \Source\

FROM base AS build
RUN go build -ldflags="-s -w"

FROM mcr.microsoft.com/windows/nanoserver:$WINDOWS_RELEASE
ARG PORT=80
ENV PORT=$PORT
ENV GIN_MODE=release
COPY --from=build \Source\cloudflare-exporter.exe \cloudflare-exporter.exe
EXPOSE $PORT
CMD ["\\cloudflare-exporter.exe"]
