name: CD Workflow
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Buildx
        uses: actions/cache@v2
        with:
          path: /tmp/buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-
      - name: Log into Container Registry
        uses: docker/login-action@v1
        with:
          registry: container.chitoku.jp
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache.new
          push: true
          tags: container.chitoku.jp/chitoku-k/cloudflare-exporter
      - name: Move cache
        run: |
          rm -rf /tmp/buildx-cache
          mv /tmp/buildx-cache{.new,}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
      - name: Set context
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: https://k8s.chitoku.jp
          k8s-secret: ${{ secrets.K8S_SECRET }}
      - name: Rollout restart
        run: kubectl rollout restart --namespace=monitor deployment/cloudflare-exporter
