name: CD Workflow
on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build (${{ matrix.target.platform }})
    strategy:
      matrix:
        target:
          - label: ubuntu-24.04
            platform: linux/amd64
            dockerfile: Dockerfile
          - label: windows-2022
            platform: windows/amd64
            dockerfile: Dockerfile.windows
            release: ltsc2022
    runs-on: ${{ matrix.target.label }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          build-args: |
            PORT=443
            WINDOWS_RELEASE=${{ matrix.target.release }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.target.platform }}
          file: ${{ matrix.target.dockerfile }}
          outputs: |
            type=image,push=true,push-by-digest=true
          tags: |
            ghcr.io/chitoku-k/cloudflare-exporter
      - name: Save digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest=${{ steps.build.outputs.imageid }}
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.target.label }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  combine:
    name: Combine images
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
      - name: Log into Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create \
            --tag=ghcr.io/chitoku-k/cloudflare-exporter:${{ github.ref_name }} \
            $(printf 'ghcr.io/chitoku-k/cloudflare-exporter@sha256:%s ' *)

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - combine
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
      - name: Set up ID token
        uses: actions/github-script@v7
        id: id-token
        with:
          result-encoding: string
          script: |
            return await core.getIDToken('k8s.chitoku.jp');
      - name: Set context
        run: |
          kubectl config set-cluster k8s.chitoku.jp --server=https://k8s.chitoku.jp
          kubectl config set-credentials github-actions --token=${{ steps.id-token.outputs.result }}
          kubectl config set-context k8s.chitoku.jp --cluster=k8s.chitoku.jp --user=github-actions --namespace=monitor
          kubectl config use-context k8s.chitoku.jp
      - name: Update image
        run: |
          kubectl set image --field-manager=github-actions deployment/cloudflare-exporter web=ghcr.io/chitoku-k/cloudflare-exporter:${{ github.ref_name }}
